// <auto-generated />
using System;
using BoulderTime.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BoulderTime.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260917100657_Phase6Notifications")]
    partial class Phase6Notifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("bouldertime")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BoulderTime.Domain.Boulders.Boulder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid")
                        .HasColumnName("gym_id");

                    b.Property<string>("HoldColor")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("hold_color");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("photo_path");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<Guid?>("RemovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("removed_by_user_id");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sector_id");

                    b.Property<Guid?>("SetterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("setter_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_boulders");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_boulders_created_by_user_id");

                    b.HasIndex("RemovedByUserId")
                        .HasDatabaseName("ix_boulders_removed_by_user_id");

                    b.HasIndex("SetterUserId")
                        .HasDatabaseName("ix_boulders_setter_user_id");

                    b.HasIndex("SectorId", "Status")
                        .HasDatabaseName("ix_boulders_sector_id_status");

                    b.HasIndex("GymId", "Status", "CreatedAt")
                        .HasDatabaseName("ix_boulders_gym_id_status_created_at");

                    b.ToTable("boulders", "bouldertime");
                });

            modelBuilder.Entity("BoulderTime.Domain.Boulders.BoulderGrade", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BoulderId")
                        .HasColumnType("uuid")
                        .HasColumnName("boulder_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("GradeSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("grade_system_id");

                    b.Property<Guid>("GradeValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("grade_value_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_boulder_grades");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_boulder_grades_created_by_user_id");

                    b.HasIndex("GradeSystemId")
                        .HasDatabaseName("ix_boulder_grades_grade_system_id");

                    b.HasIndex("GradeValueId")
                        .HasDatabaseName("ix_boulder_grades_grade_value_id");

                    b.HasIndex("BoulderId", "GradeSystemId")
                        .IsUnique()
                        .HasDatabaseName("ix_boulder_grades_boulder_id_grade_system_id")
                        .HasFilter("source = 'Staff'");

                    b.ToTable("boulder_grades", "bouldertime");
                });

            modelBuilder.Entity("BoulderTime.Domain.Candidates.GymCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("GymId")
                        .HasColumnType("uuid")
                        .HasColumnName("gym_id");

                    b.Property<string>("GymName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("gym_name");

                    b.Property<DateTimeOffset?>("HandledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("handled_at");

                    b.Property<Guid?>("HandledByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("handled_by_user_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("OfficialEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("official_email");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubmittedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by_user_id");

                    b.Property<string>("Website")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_gym_candidates");

                    b.HasIndex("GymId")
                        .HasDatabaseName("ix_gym_candidates_gym_id");

                    b.HasIndex("HandledByUserId")
                        .HasDatabaseName("ix_gym_candidates_handled_by_user_id");

                    b.HasIndex("SubmittedByUserId")
                        .HasDatabaseName("ix_gym_candidates_submitted_by_user_id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_gym_candidates_status_created_at");

                    b.ToTable("gym_candidates", "bouldertime");
                });

            modelBuilder.Entity("BoulderTime.Domain.Climbing.BoulderAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<Guid>("BoulderId")
                        .HasColumnType("uuid")
                        .HasColumnName("boulder_id");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean")
                        .HasColumnName("completed");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_boulder_attempts");

                    b.HasIndex("BoulderId")
                        .HasDatabaseName("ix_boulder_attempts_boulder_id");

                    b.HasIndex("UserId", "BoulderId")
                        .IsUnique()
                        .HasDatabaseName("ix_boulder_attempts_user_id_boulder_id");

                    b.HasIndex("UserId", "Completed", "CompletedAt")
                        .HasDatabaseName("ix_boulder_attempts_user_id_completed_completed_at");

                    b.ToTable("boulder_attempts", "bouldertime", t =>
                        {
                            t.HasCheckConstraint("ck_boulder_attempts_attempts", "attempts >= 0 AND attempts <= 999");
                        });
                });

            modelBuilder.Entity("BoulderTime.Domain.Climbing.BoulderRating", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BoulderId")
                        .HasColumnType("uuid")
                        .HasColumnName("boulder_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_boulder_ratings");

                    b.HasIndex("BoulderId")
                        .HasDatabaseName("ix_boulder_ratings_boulder_id");

                    b.HasIndex("UserId", "BoulderId")
                        .IsUnique()
                        .HasDatabaseName("ix_boulder_ratings_user_id_boulder_id");

                    b.ToTable("boulder_ratings", "bouldertime", t =>
                        {
                            t.HasCheckConstraint("ck_boulder_ratings_rating", "rating BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("BoulderTime.Domain.Community.BoulderBeta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BoulderId")
                        .HasColumnType("uuid")
                        .HasColumnName("boulder_id");

                    b.Property<string>("Caption")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("caption");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("storage_path");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_boulder_betas");

                    b.HasIndex("BoulderId")
                        .IsUnique()
                        .HasDatabaseName("ix_boulder_betas_boulder_id");

                    b.HasIndex("UploadedByUserId")
                        .HasDatabaseName("ix_boulder_betas_uploaded_by_user_id");

                    b.ToTable("boulder_betas", "bouldertime");
                });

            modelBuilder.Entity("BoulderTime.Domain.Community.BoulderVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BoulderId")
                        .HasColumnType("uuid")
                        .HasColumnName("boulder_id");

                    b.Property<string>("Caption")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("caption");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("storage_path");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_boulder_videos");

                    b.HasIndex("ReviewedByUserId")
                        .HasDatabaseName("ix_boulder_videos_reviewed_by_user_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_boulder_videos_user_id");

                    b.HasIndex("BoulderId", "Status")
                        .HasDatabaseName("ix_boulder_videos_boulder_id_status");

                    b.HasIndex("Status", "UpdatedAt")
                        .HasDatabaseName("ix_boulder_videos_status_updated_at");

                    b.ToTable("boulder_videos", "bouldertime");
                });

            modelBuilder.Entity("BoulderTime.Domain.Community.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BoulderId")
                        .HasColumnType("uuid")
                        .HasColumnName("boulder_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("EditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_comments");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_comments_user_id");

                    b.HasIndex("BoulderId", "CreatedAt")
                        .HasDatabaseName("ix_comments_boulder_id_created_at");

                    b.ToTable("comments", "bouldertime");
                });

            modelBuilder.Entity("BoulderTime.Domain.Community.CommentLike", b =>
                {
                    b.Property<Guid>("CommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("comment_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("CommentId", "UserId")
                        .HasName("pk_comment_likes");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_comment_likes_user_id");

                    b.ToTable("comment_likes", "bouldertime");
                });

            modelBuilder.Entity("BoulderTime.Domain.Community.GradeSuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BoulderId")
                        .HasColumnType("uuid")
                        .HasColumnName("boulder_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GradeSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("grade_system_id");

                    b.Property<Guid>("GradeValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("grade_value_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_grade_suggestions");

                    b.HasIndex("GradeSystemId")
                        .HasDatabaseName("ix_grade_suggestions_grade_system_id");

                    b.HasIndex("GradeValueId")
                        .HasDatabaseName("ix_grade_suggestions_grade_value_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_grade_suggestions_user_id");

                    b.HasIndex("BoulderId", "GradeValueId")
                        .HasDatabaseName("ix_grade_suggestions_boulder_id_grade_value_id");

                    b.HasIndex("BoulderId", "UserId", "GradeSystemId")
                        .IsUnique()
                        .HasDatabaseName("ix_grade_suggestions_boulder_id_user_id_grade_system_id");

                    b.ToTable("grade_suggestions", "bouldertime");
                });

            modelBuilder.Entity("BoulderTime.Domain.Community.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid")
                        .HasColumnName("gym_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("reason");

                    b.Property<Guid>("ReportedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reported_by_user_id");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("resolution_note");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_reports");

                    b.HasIndex("ReviewedByUserId")
                        .HasDatabaseName("ix_reports_reviewed_by_user_id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_reports_status_created_at");

                    b.HasIndex("GymId", "Status", "CreatedAt")
                        .HasDatabaseName("ix_reports_gym_id_status_created_at");

                    b.HasIndex("ReportedByUserId", "EntityType", "EntityId")
                        .IsUnique()
                        .HasDatabaseName("ix_reports_reported_by_user_id_entity_type_entity_id")
                        .HasFilter("status = 'Pending'");

                    b.ToTable("reports", "bouldertime");
                });

            modelBuilder.Entity("BoulderTime.Domain.Follows.BoulderFollow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BoulderId")
                        .HasColumnType("uuid")
                        .HasColumnName("boulder_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("notifications_enabled");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_boulder_follows");

                    b.HasIndex("BoulderId")
                        .HasDatabaseName("ix_boulder_follows_boulder_id");

                    b.HasIndex("UserId", "BoulderId")
                        .IsUnique()
                        .HasDatabaseName("ix_boulder_follows_user_id_boulder_id");

                    b.ToTable("boulder_follows", "bouldertime");
                });

            modelBuilder.Entity("BoulderTime.Domain.Follows.GymFollow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid")
                        .HasColumnName("gym_id");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean")
                        .HasColumnName("is_favorite");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("notifications_enabled");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_gym_follows");

                    b.HasIndex("GymId")
                        .HasDatabaseName("ix_gym_follows_gym_id");

                    b.HasIndex("UserId", "GymId")
                        .IsUnique()
                        .HasDatabaseName("ix_gym_follows_user_id_gym_id");

                    b.ToTable("gym_follows", "bouldertime");
                });

            modelBuilder.Entity("BoulderTime.Domain.Follows.SectorFollow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("notifications_enabled");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sector_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sector_follows");

                    b.HasIndex("SectorId")
                        .HasDatabaseName("ix_sector_follows_sector_id");

                    b.HasIndex("UserId", "SectorId")
                        .IsUnique()
                        .HasDatabaseName("ix_sector_follows_user_id_sector_id");

                    b.ToTable("sector_follows", "bouldertime");
                });

            modelBuilder.Entity("BoulderTime.Domain.Grading.GradeSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid")
                        .HasColumnName("gym_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_grade_systems");

                    b.HasIndex("GymId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_grade_systems_gym_id_name");

                    b.HasIndex("GymId", "SortOrder")
                        .HasDatabaseName("ix_grade_systems_gym_id_sort_order");

                    b.ToTable("grade_systems", "bouldertime");
                });

            modelBuilder.Entity("BoulderTime.Domain.Grading.GradeValue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color_hex");

                    b.Property<Guid>("GradeSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("grade_system_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("label");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.HasKey("Id")
                        .HasName("pk_grade_values");

                    b.HasIndex("GradeSystemId", "Rank")
                        .HasDatabaseName("ix_grade_values_grade_system_id_rank");

                    b.ToTable("grade_values", "bouldertime");
                });

            modelBuilder.Entity("BoulderTime.Domain.Gyms.Gym", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("cover_image_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("phone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(88)
                        .HasColumnType("character varying(88)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Website")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_gyms");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_gyms_slug");

                    b.HasIndex("Status", "City")
                        .HasDatabaseName("ix_gyms_status_city");

                    b.HasIndex("Status", "Name")
                        .HasDatabaseName("ix_gyms_status_name");

                    b.ToTable("gyms", "bouldertime");
                });

            modelBuilder.Entity("BoulderTime.Domain.Gyms.Sector", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid")
                        .HasColumnName("gym_id");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sectors");

                    b.HasIndex("GymId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_sectors_gym_id_name");

                    b.HasIndex("GymId", "SortOrder")
                        .HasDatabaseName("ix_sectors_gym_id_sort_order");

                    b.ToTable("sectors", "bouldertime");
                });

            modelBuilder.Entity("BoulderTime.Domain.Notifications.GymAnnouncement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("EventDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_date");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid")
                        .HasColumnName("gym_id");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("image_path");

                    b.Property<bool>("NotifyFollowers")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_followers");

                    b.Property<Guid?>("SectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sector_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_gym_announcements");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_gym_announcements_created_by_user_id");

                    b.HasIndex("SectorId")
                        .HasDatabaseName("ix_gym_announcements_sector_id");

                    b.HasIndex("GymId", "CreatedAt")
                        .HasDatabaseName("ix_gym_announcements_gym_id_created_at");

                    b.ToTable("gym_announcements", "bouldertime");
                });

            modelBuilder.Entity("BoulderTime.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("body");

                    b.Property<string>("CollapseKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("collapse_key");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("GymId")
                        .HasColumnType("uuid")
                        .HasColumnName("gym_id");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("link");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<Guid>("RelatedEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_entity_id");

                    b.Property<string>("RelatedEntityType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("related_entity_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("CollapseKey", "UserId")
                        .HasDatabaseName("ix_notifications_collapse_key_user_id")
                        .HasFilter("read_at IS NULL AND collapse_key IS NOT NULL");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_notifications_user_id_created_at");

                    b.HasIndex("UserId", "ReadAt")
                        .HasDatabaseName("ix_notifications_user_id_read_at");

                    b.ToTable("notifications", "bouldertime");
                });

            modelBuilder.Entity("BoulderTime.Domain.Notifications.NotificationSettings", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("BoulderUpdates")
                        .HasColumnType("boolean")
                        .HasColumnName("boulder_updates");

                    b.Property<bool>("GymUpdates")
                        .HasColumnType("boolean")
                        .HasColumnName("gym_updates");

                    b.Property<bool>("MyContent")
                        .HasColumnType("boolean")
                        .HasColumnName("my_content");

                    b.Property<bool>("SectorUpdates")
                        .HasColumnType("boolean")
                        .HasColumnName("sector_updates");

                    b.HasKey("UserId")
                        .HasName("pk_notification_settings");

                    b.ToTable("notification_settings", "bouldertime");
                });

            modelBuilder.Entity("BoulderTime.Domain.Staff.GymStaffMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid")
                        .HasColumnName("gym_id");

                    b.Property<Guid?>("InvitedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by_user_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_gym_staff");

                    b.HasIndex("InvitedByUserId")
                        .HasDatabaseName("ix_gym_staff_invited_by_user_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_gym_staff_user_id");

                    b.HasIndex("GymId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_gym_staff_gym_id_user_id");

                    b.ToTable("gym_staff", "bouldertime");
                });

            modelBuilder.Entity("BoulderTime.Domain.Staff.StaffInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AcceptedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("accepted_by_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid")
                        .HasColumnName("gym_id");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by_user_id");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_staff_invitations");

                    b.HasIndex("AcceptedByUserId")
                        .HasDatabaseName("ix_staff_invitations_accepted_by_user_id");

                    b.HasIndex("InvitedByUserId")
                        .HasDatabaseName("ix_staff_invitations_invited_by_user_id");

                    b.HasIndex("Email", "Status")
                        .HasDatabaseName("ix_staff_invitations_email_status");

                    b.HasIndex("GymId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_staff_invitations_gym_id_email")
                        .HasFilter("status = 'Pending'");

                    b.ToTable("staff_invitations", "bouldertime");
                });

            modelBuilder.Entity("BoulderTime.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsPlatformAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_platform_admin");

                    b.Property<string>("ProfileVisibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Public")
                        .HasColumnName("profile_visibility");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", "bouldertime");
                });

            modelBuilder.Entity("BoulderTime.Domain.Boulders.Boulder", b =>
                {
                    b.HasOne("BoulderTime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_boulders_users_created_by_user_id");

                    b.HasOne("BoulderTime.Domain.Gyms.Gym", null)
                        .WithMany()
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_boulders_gyms_gym_id");

                    b.HasOne("BoulderTime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("RemovedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_boulders_users_removed_by_user_id");

                    b.HasOne("BoulderTime.Domain.Gyms.Sector", null)
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_boulders_sectors_sector_id");

                    b.HasOne("BoulderTime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("SetterUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_boulders_users_setter_user_id");
                });

            modelBuilder.Entity("BoulderTime.Domain.Boulders.BoulderGrade", b =>
                {
                    b.HasOne("BoulderTime.Domain.Boulders.Boulder", null)
                        .WithMany()
                        .HasForeignKey("BoulderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_boulder_grades_boulders_boulder_id");

                    b.HasOne("BoulderTime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_boulder_grades_users_created_by_user_id");

                    b.HasOne("BoulderTime.Domain.Grading.GradeSystem", null)
                        .WithMany()
                        .HasForeignKey("GradeSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_boulder_grades_grade_systems_grade_system_id");

                    b.HasOne("BoulderTime.Domain.Grading.GradeValue", null)
                        .WithMany()
                        .HasForeignKey("GradeValueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_boulder_grades_grade_values_grade_value_id");
                });

            modelBuilder.Entity("BoulderTime.Domain.Candidates.GymCandidate", b =>
                {
                    b.HasOne("BoulderTime.Domain.Gyms.Gym", null)
                        .WithMany()
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_gym_candidates_gyms_gym_id");

                    b.HasOne("BoulderTime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("HandledByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_gym_candidates_users_handled_by_user_id");

                    b.HasOne("BoulderTime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_gym_candidates_users_submitted_by_user_id");
                });

            modelBuilder.Entity("BoulderTime.Domain.Climbing.BoulderAttempt", b =>
                {
                    b.HasOne("BoulderTime.Domain.Boulders.Boulder", null)
                        .WithMany()
                        .HasForeignKey("BoulderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_boulder_attempts_boulders_boulder_id");

                    b.HasOne("BoulderTime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_boulder_attempts_users_user_id");
                });

            modelBuilder.Entity("BoulderTime.Domain.Climbing.BoulderRating", b =>
                {
                    b.HasOne("BoulderTime.Domain.Boulders.Boulder", null)
                        .WithMany()
                        .HasForeignKey("BoulderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_boulder_ratings_boulders_boulder_id");

                    b.HasOne("BoulderTime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_boulder_ratings_users_user_id");
                });

            modelBuilder.Entity("BoulderTime.Domain.Community.BoulderBeta", b =>
                {
                    b.HasOne("BoulderTime.Domain.Boulders.Boulder", null)
                        .WithMany()
                        .HasForeignKey("BoulderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_boulder_betas_boulders_boulder_id");

                    b.HasOne("BoulderTime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_boulder_betas_users_uploaded_by_user_id");
                });

            modelBuilder.Entity("BoulderTime.Domain.Community.BoulderVideo", b =>
                {
                    b.HasOne("BoulderTime.Domain.Boulders.Boulder", null)
                        .WithMany()
                        .HasForeignKey("BoulderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_boulder_videos_boulders_boulder_id");

                    b.HasOne("BoulderTime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_boulder_videos_users_reviewed_by_user_id");

                    b.HasOne("BoulderTime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_boulder_videos_users_user_id");
                });

            modelBuilder.Entity("BoulderTime.Domain.Community.Comment", b =>
                {
                    b.HasOne("BoulderTime.Domain.Boulders.Boulder", null)
                        .WithMany()
                        .HasForeignKey("BoulderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comments_boulders_boulder_id");

                    b.HasOne("BoulderTime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comments_users_user_id");
                });

            modelBuilder.Entity("BoulderTime.Domain.Community.CommentLike", b =>
                {
                    b.HasOne("BoulderTime.Domain.Community.Comment", null)
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_likes_comments_comment_id");

                    b.HasOne("BoulderTime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_likes_users_user_id");
                });

            modelBuilder.Entity("BoulderTime.Domain.Community.GradeSuggestion", b =>
                {
                    b.HasOne("BoulderTime.Domain.Boulders.Boulder", null)
                        .WithMany()
                        .HasForeignKey("BoulderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_grade_suggestions_boulders_boulder_id");

                    b.HasOne("BoulderTime.Domain.Grading.GradeSystem", null)
                        .WithMany()
                        .HasForeignKey("GradeSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_grade_suggestions_grade_systems_grade_system_id");

                    b.HasOne("BoulderTime.Domain.Grading.GradeValue", null)
                        .WithMany()
                        .HasForeignKey("GradeValueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_grade_suggestions_grade_values_grade_value_id");

                    b.HasOne("BoulderTime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_grade_suggestions_users_user_id");
                });

            modelBuilder.Entity("BoulderTime.Domain.Community.Report", b =>
                {
                    b.HasOne("BoulderTime.Domain.Gyms.Gym", null)
                        .WithMany()
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reports_gyms_gym_id");

                    b.HasOne("BoulderTime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ReportedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reports_users_reported_by_user_id");

                    b.HasOne("BoulderTime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_reports_users_reviewed_by_user_id");
                });

            modelBuilder.Entity("BoulderTime.Domain.Follows.BoulderFollow", b =>
                {
                    b.HasOne("BoulderTime.Domain.Boulders.Boulder", null)
                        .WithMany()
                        .HasForeignKey("BoulderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_boulder_follows_boulders_boulder_id");

                    b.HasOne("BoulderTime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_boulder_follows_users_user_id");
                });

            modelBuilder.Entity("BoulderTime.Domain.Follows.GymFollow", b =>
                {
                    b.HasOne("BoulderTime.Domain.Gyms.Gym", null)
                        .WithMany()
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gym_follows_gyms_gym_id");

                    b.HasOne("BoulderTime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gym_follows_users_user_id");
                });

            modelBuilder.Entity("BoulderTime.Domain.Follows.SectorFollow", b =>
                {
                    b.HasOne("BoulderTime.Domain.Gyms.Sector", null)
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sector_follows_sectors_sector_id");

                    b.HasOne("BoulderTime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sector_follows_users_user_id");
                });

            modelBuilder.Entity("BoulderTime.Domain.Grading.GradeSystem", b =>
                {
                    b.HasOne("BoulderTime.Domain.Gyms.Gym", null)
                        .WithMany()
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_grade_systems_gyms_gym_id");
                });

            modelBuilder.Entity("BoulderTime.Domain.Grading.GradeValue", b =>
                {
                    b.HasOne("BoulderTime.Domain.Grading.GradeSystem", null)
                        .WithMany()
                        .HasForeignKey("GradeSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_grade_values_grade_systems_grade_system_id");
                });

            modelBuilder.Entity("BoulderTime.Domain.Gyms.Sector", b =>
                {
                    b.HasOne("BoulderTime.Domain.Gyms.Gym", null)
                        .WithMany()
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sectors_gyms_gym_id");
                });

            modelBuilder.Entity("BoulderTime.Domain.Notifications.GymAnnouncement", b =>
                {
                    b.HasOne("BoulderTime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_gym_announcements_users_created_by_user_id");

                    b.HasOne("BoulderTime.Domain.Gyms.Gym", null)
                        .WithMany()
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_gym_announcements_gyms_gym_id");

                    b.HasOne("BoulderTime.Domain.Gyms.Sector", null)
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_gym_announcements_sectors_sector_id");
                });

            modelBuilder.Entity("BoulderTime.Domain.Notifications.Notification", b =>
                {
                    b.HasOne("BoulderTime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");
                });

            modelBuilder.Entity("BoulderTime.Domain.Notifications.NotificationSettings", b =>
                {
                    b.HasOne("BoulderTime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_settings_users_user_id");
                });

            modelBuilder.Entity("BoulderTime.Domain.Staff.GymStaffMember", b =>
                {
                    b.HasOne("BoulderTime.Domain.Gyms.Gym", null)
                        .WithMany()
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_gym_staff_gyms_gym_id");

                    b.HasOne("BoulderTime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_gym_staff_users_invited_by_user_id");

                    b.HasOne("BoulderTime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_gym_staff_users_user_id");
                });

            modelBuilder.Entity("BoulderTime.Domain.Staff.StaffInvitation", b =>
                {
                    b.HasOne("BoulderTime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("AcceptedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_staff_invitations_users_accepted_by_user_id");

                    b.HasOne("BoulderTime.Domain.Gyms.Gym", null)
                        .WithMany()
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_staff_invitations_gyms_gym_id");

                    b.HasOne("BoulderTime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_staff_invitations_users_invited_by_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
