// <auto-generated />
using System;
using BoulderTime.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BoulderTime.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("bouldertime")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BoulderTime.Domain.Boulders.Boulder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid")
                        .HasColumnName("gym_id");

                    b.Property<string>("HoldColor")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("hold_color");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("photo_path");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<Guid?>("RemovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("removed_by_user_id");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sector_id");

                    b.Property<Guid?>("SetterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("setter_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_boulders");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_boulders_created_by_user_id");

                    b.HasIndex("RemovedByUserId")
                        .HasDatabaseName("ix_boulders_removed_by_user_id");

                    b.HasIndex("SetterUserId")
                        .HasDatabaseName("ix_boulders_setter_user_id");

                    b.HasIndex("SectorId", "Status")
                        .HasDatabaseName("ix_boulders_sector_id_status");

                    b.HasIndex("GymId", "Status", "CreatedAt")
                        .HasDatabaseName("ix_boulders_gym_id_status_created_at");

                    b.ToTable("boulders", "bouldertime");
                });

            modelBuilder.Entity("BoulderTime.Domain.Boulders.BoulderGrade", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BoulderId")
                        .HasColumnType("uuid")
                        .HasColumnName("boulder_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("GradeSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("grade_system_id");

                    b.Property<Guid>("GradeValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("grade_value_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_boulder_grades");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_boulder_grades_created_by_user_id");

                    b.HasIndex("GradeSystemId")
                        .HasDatabaseName("ix_boulder_grades_grade_system_id");

                    b.HasIndex("GradeValueId")
                        .HasDatabaseName("ix_boulder_grades_grade_value_id");

                    b.HasIndex("BoulderId", "GradeSystemId")
                        .IsUnique()
                        .HasDatabaseName("ix_boulder_grades_boulder_id_grade_system_id")
                        .HasFilter("source = 'Staff'");

                    b.ToTable("boulder_grades", "bouldertime");
                });

            modelBuilder.Entity("BoulderTime.Domain.Candidates.GymCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("GymId")
                        .HasColumnType("uuid")
                        .HasColumnName("gym_id");

                    b.Property<string>("GymName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("gym_name");

                    b.Property<DateTimeOffset?>("HandledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("handled_at");

                    b.Property<Guid?>("HandledByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("handled_by_user_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("OfficialEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("official_email");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubmittedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by_user_id");

                    b.Property<string>("Website")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_gym_candidates");

                    b.HasIndex("GymId")
                        .HasDatabaseName("ix_gym_candidates_gym_id");

                    b.HasIndex("HandledByUserId")
                        .HasDatabaseName("ix_gym_candidates_handled_by_user_id");

                    b.HasIndex("SubmittedByUserId")
                        .HasDatabaseName("ix_gym_candidates_submitted_by_user_id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_gym_candidates_status_created_at");

                    b.ToTable("gym_candidates", "bouldertime");
                });

            modelBuilder.Entity("BoulderTime.Domain.Grading.GradeSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid")
                        .HasColumnName("gym_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_grade_systems");

                    b.HasIndex("GymId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_grade_systems_gym_id_name");

                    b.HasIndex("GymId", "SortOrder")
                        .HasDatabaseName("ix_grade_systems_gym_id_sort_order");

                    b.ToTable("grade_systems", "bouldertime");
                });

            modelBuilder.Entity("BoulderTime.Domain.Grading.GradeValue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color_hex");

                    b.Property<Guid>("GradeSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("grade_system_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("label");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.HasKey("Id")
                        .HasName("pk_grade_values");

                    b.HasIndex("GradeSystemId", "Rank")
                        .HasDatabaseName("ix_grade_values_grade_system_id_rank");

                    b.ToTable("grade_values", "bouldertime");
                });

            modelBuilder.Entity("BoulderTime.Domain.Gyms.Gym", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("cover_image_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("phone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(88)
                        .HasColumnType("character varying(88)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Website")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_gyms");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_gyms_slug");

                    b.HasIndex("Status", "City")
                        .HasDatabaseName("ix_gyms_status_city");

                    b.HasIndex("Status", "Name")
                        .HasDatabaseName("ix_gyms_status_name");

                    b.ToTable("gyms", "bouldertime");
                });

            modelBuilder.Entity("BoulderTime.Domain.Gyms.Sector", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid")
                        .HasColumnName("gym_id");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sectors");

                    b.HasIndex("GymId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_sectors_gym_id_name");

                    b.HasIndex("GymId", "SortOrder")
                        .HasDatabaseName("ix_sectors_gym_id_sort_order");

                    b.ToTable("sectors", "bouldertime");
                });

            modelBuilder.Entity("BoulderTime.Domain.Staff.GymStaffMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid")
                        .HasColumnName("gym_id");

                    b.Property<Guid?>("InvitedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by_user_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_gym_staff");

                    b.HasIndex("InvitedByUserId")
                        .HasDatabaseName("ix_gym_staff_invited_by_user_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_gym_staff_user_id");

                    b.HasIndex("GymId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_gym_staff_gym_id_user_id");

                    b.ToTable("gym_staff", "bouldertime");
                });

            modelBuilder.Entity("BoulderTime.Domain.Staff.StaffInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AcceptedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("accepted_by_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid")
                        .HasColumnName("gym_id");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by_user_id");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_staff_invitations");

                    b.HasIndex("AcceptedByUserId")
                        .HasDatabaseName("ix_staff_invitations_accepted_by_user_id");

                    b.HasIndex("InvitedByUserId")
                        .HasDatabaseName("ix_staff_invitations_invited_by_user_id");

                    b.HasIndex("Email", "Status")
                        .HasDatabaseName("ix_staff_invitations_email_status");

                    b.HasIndex("GymId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_staff_invitations_gym_id_email")
                        .HasFilter("status = 'Pending'");

                    b.ToTable("staff_invitations", "bouldertime");
                });

            modelBuilder.Entity("BoulderTime.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsPlatformAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_platform_admin");

                    b.Property<string>("ProfileVisibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Public")
                        .HasColumnName("profile_visibility");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", "bouldertime");
                });

            modelBuilder.Entity("BoulderTime.Domain.Boulders.Boulder", b =>
                {
                    b.HasOne("BoulderTime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_boulders_users_created_by_user_id");

                    b.HasOne("BoulderTime.Domain.Gyms.Gym", null)
                        .WithMany()
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_boulders_gyms_gym_id");

                    b.HasOne("BoulderTime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("RemovedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_boulders_users_removed_by_user_id");

                    b.HasOne("BoulderTime.Domain.Gyms.Sector", null)
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_boulders_sectors_sector_id");

                    b.HasOne("BoulderTime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("SetterUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_boulders_users_setter_user_id");
                });

            modelBuilder.Entity("BoulderTime.Domain.Boulders.BoulderGrade", b =>
                {
                    b.HasOne("BoulderTime.Domain.Boulders.Boulder", null)
                        .WithMany()
                        .HasForeignKey("BoulderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_boulder_grades_boulders_boulder_id");

                    b.HasOne("BoulderTime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_boulder_grades_users_created_by_user_id");

                    b.HasOne("BoulderTime.Domain.Grading.GradeSystem", null)
                        .WithMany()
                        .HasForeignKey("GradeSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_boulder_grades_grade_systems_grade_system_id");

                    b.HasOne("BoulderTime.Domain.Grading.GradeValue", null)
                        .WithMany()
                        .HasForeignKey("GradeValueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_boulder_grades_grade_values_grade_value_id");
                });

            modelBuilder.Entity("BoulderTime.Domain.Candidates.GymCandidate", b =>
                {
                    b.HasOne("BoulderTime.Domain.Gyms.Gym", null)
                        .WithMany()
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_gym_candidates_gyms_gym_id");

                    b.HasOne("BoulderTime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("HandledByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_gym_candidates_users_handled_by_user_id");

                    b.HasOne("BoulderTime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_gym_candidates_users_submitted_by_user_id");
                });

            modelBuilder.Entity("BoulderTime.Domain.Grading.GradeSystem", b =>
                {
                    b.HasOne("BoulderTime.Domain.Gyms.Gym", null)
                        .WithMany()
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_grade_systems_gyms_gym_id");
                });

            modelBuilder.Entity("BoulderTime.Domain.Grading.GradeValue", b =>
                {
                    b.HasOne("BoulderTime.Domain.Grading.GradeSystem", null)
                        .WithMany()
                        .HasForeignKey("GradeSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_grade_values_grade_systems_grade_system_id");
                });

            modelBuilder.Entity("BoulderTime.Domain.Gyms.Sector", b =>
                {
                    b.HasOne("BoulderTime.Domain.Gyms.Gym", null)
                        .WithMany()
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sectors_gyms_gym_id");
                });

            modelBuilder.Entity("BoulderTime.Domain.Staff.GymStaffMember", b =>
                {
                    b.HasOne("BoulderTime.Domain.Gyms.Gym", null)
                        .WithMany()
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_gym_staff_gyms_gym_id");

                    b.HasOne("BoulderTime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_gym_staff_users_invited_by_user_id");

                    b.HasOne("BoulderTime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_gym_staff_users_user_id");
                });

            modelBuilder.Entity("BoulderTime.Domain.Staff.StaffInvitation", b =>
                {
                    b.HasOne("BoulderTime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("AcceptedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_staff_invitations_users_accepted_by_user_id");

                    b.HasOne("BoulderTime.Domain.Gyms.Gym", null)
                        .WithMany()
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_staff_invitations_gyms_gym_id");

                    b.HasOne("BoulderTime.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_staff_invitations_users_invited_by_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
