#!/usr/bin/env bash
# Runs the whole BoulderTime stack inside a GitHub Codespace (or any Linux box with Docker):
#   local Supabase (Postgres + Auth + Storage) → migrations + demo data → API → frontend.
# Usage:
#   bash scripts/dev.sh           start everything and print the link
#   bash scripts/dev.sh promote   after signing up: make every local user admin + owner of the demo gyms
#   bash scripts/dev.sh stop      stop everything
set -uo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"; cd "$ROOT"
export DOTNET_CLI_TELEMETRY_OPTOUT=1 DOTNET_NOLOGO=1 ASPNETCORE_ENVIRONMENT=Development
export PATH="$HOME/.dotnet:$HOME/.dotnet/tools:$PATH"
LOGS="/tmp/bouldertime"; mkdir -p "$LOGS"
# Pinned: CLI >= 2.112.0 fails to initialise the schema inside containers such as Codespaces
# (realtime migration can't switch user; supabase/cli#6462). Bump only after that is fixed.
SUPA_VERSION="2.111.0"
SUPA="npx -y supabase@$SUPA_VERSION"
step() { printf "\n\033[1;38;5;208m▶ %s\033[0m\n" "$*"; }
fail() { printf "\n\033[1;31m✖ %s\033[0m\n" "$*"; exit 1; }

if [ "${1:-}" = "stop" ]; then
  pkill -f "BoulderTime.Api" 2>/dev/null; pkill -f "vite" 2>/dev/null
  $SUPA stop --workdir database >/dev/null 2>&1
  echo "Stopped."; exit 0
fi

if [ "${1:-}" = "promote" ]; then
  cd backend && dotnet run --project src/BoulderTime.Api -- dev-promote-all
  echo "Reload the app in your browser."; exit 0
fi

step "1/6 .NET 8"
if ! dotnet --list-sdks 2>/dev/null | grep -q '^8\.'; then
  curl -sSL https://dot.net/v1/dotnet-install.sh | bash -s -- --channel 8.0 >/dev/null || fail ".NET install failed"
  export DOTNET_ROOT="$HOME/.dotnet"
fi
dotnet tool install --global dotnet-ef --version 8.0.11 >/dev/null 2>&1 || true
echo "ok"

step "2/6 Local Supabase (first run downloads images: a few minutes)"
docker info >/dev/null 2>&1 || fail "Docker is not available in this environment."
CONFIG=database/supabase/config.toml
MARKER="# bouldertime: generated by supabase CLI $SUPA_VERSION"
if [ -f "$CONFIG" ] && ! grep -qF "$MARKER" "$CONFIG"; then
  # Config generated by a different CLI version: start clean.
  $SUPA stop --workdir database --no-backup >/dev/null 2>&1
  npx -y supabase@latest stop --workdir database --no-backup >/dev/null 2>&1
  rm -f "$CONFIG"
fi
if [ ! -f "$CONFIG" ]; then
  (cd database && echo n | $SUPA init >/dev/null 2>&1) || fail "supabase init failed"
  # Only database, auth and the API gateway are needed right now. Storage is enabled in Phase 3.
  awk '
    /^\[/ { section=$0; off = (section ~ /^\[(realtime|studio|edge_runtime|analytics|inbucket|local_smtp|storage)\]$/) }
    off && /^enabled *=/ { print "enabled = false"; next }
    { print }
  ' "$CONFIG" > "$CONFIG.tmp" && mv "$CONFIG.tmp" "$CONFIG"
  echo "$MARKER" >> "$CONFIG"
fi

start_supabase() { $SUPA start --workdir database --debug >> "$LOGS/supabase.log" 2>&1; }
: > "$LOGS/supabase.log"
if ! start_supabase; then
  echo "First attempt failed, retrying from a clean state..."
  $SUPA stop --workdir database --no-backup >> "$LOGS/supabase.log" 2>&1
  if ! start_supabase; then
    DIAG="$ROOT/dev-log.txt"
    {
      echo "== supabase CLI $SUPA_VERSION =="; tail -80 "$LOGS/supabase.log"
      echo; echo "== containers =="; docker ps -a --format '{{.Names}}  {{.Status}}  {{.Image}}'
      for c in $(docker ps -a --filter "name=supabase_" --filter "status=exited" --format '{{.Names}}'); do
        echo; echo "== logs: $c =="; docker logs --tail 40 "$c" 2>&1
      done
      echo; echo "== resources =="; df -h / | tail -1; free -m | head -2
    } > "$DIAG" 2>&1
    git add "$DIAG" >/dev/null 2>&1 && git commit -qm "dev.sh diagnostics" >/dev/null 2>&1 && git push -q origin HEAD >/dev/null 2>&1 \
      && echo "Diagnostics published to dev-log.txt in the repository."
    fail "Supabase did not start"
  fi
fi
STATUS="$($SUPA status --workdir database -o env 2>/dev/null)"
val() { echo "$STATUS" | grep -E "^$1=" | head -1 | cut -d= -f2- | tr -d '"'; }
ANON="$(val PUBLISHABLE_KEY)"; [ -z "$ANON" ] && ANON="$(val ANON_KEY)"
JWT_SECRET="$(val JWT_SECRET)"
[ -n "$ANON" ] || fail "Could not read the Supabase anon key (see: $SUPA status --workdir database)"
echo "ok"

step "3/6 Database migrations + demo gyms"
export ConnectionStrings__Database="Host=127.0.0.1;Port=54322;Database=postgres;Username=postgres;Password=postgres"
export Supabase__Url="http://127.0.0.1:54321" Supabase__JwtSecret="$JWT_SECRET"
(cd backend && dotnet run --project src/BoulderTime.Api -- migrate > "$LOGS/migrate.log" 2>&1) || { tail -30 "$LOGS/migrate.log"; fail "Migrations failed"; }
(cd backend && dotnet run --project src/BoulderTime.Api -- seed >> "$LOGS/migrate.log" 2>&1) || { tail -30 "$LOGS/migrate.log"; fail "Seeding failed"; }
echo "ok"

step "4/6 API"
pkill -f "BoulderTime.Api" 2>/dev/null; sleep 1
(cd backend && ASPNETCORE_URLS=http://127.0.0.1:5080 nohup dotnet run --project src/BoulderTime.Api --no-launch-profile > "$LOGS/api.log" 2>&1 &)
for i in $(seq 1 60); do curl -sf http://127.0.0.1:5080/api/health >/dev/null && break; sleep 2; done
curl -sf http://127.0.0.1:5080/api/health >/dev/null || { tail -30 "$LOGS/api.log"; fail "API did not start"; }
echo "ok"

step "5/6 Frontend"
cat > frontend/.env.local << ENV
VITE_SUPABASE_URL=/supabase
VITE_SUPABASE_ANON_KEY=$ANON
VITE_API_BASE_URL=/
ENV
(cd frontend && [ -d node_modules ] || npm ci --silent) >/dev/null 2>&1
pkill -f "vite" 2>/dev/null; sleep 1
(cd frontend && nohup npm run dev > "$LOGS/web.log" 2>&1 &)
for i in $(seq 1 40); do curl -sf http://127.0.0.1:5173 >/dev/null && break; sleep 1; done
curl -sf http://127.0.0.1:5173 >/dev/null || { tail -20 "$LOGS/web.log"; fail "Frontend did not start"; }
echo "ok"

step "6/6 Ready"
if [ -n "${CODESPACE_NAME:-}" ]; then
  URL="https://${CODESPACE_NAME}-5173.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN:-app.github.dev}"
else
  URL="http://localhost:5173"
fi
printf "\n  Open BoulderTime:  \033[1;4m%s\033[0m\n\n" "$URL"
echo "  1. Create an account (email + any password, no confirmation needed locally)."
echo "  2. To unlock staff and admin areas:  bash scripts/dev.sh promote"
echo "  Logs: $LOGS   ·   Stop: bash scripts/dev.sh stop"
